<?php
/**
 * Created by PhpStorm.
 * User: Allan Wiz
 * Date: 10/26/15
 * Time: 4:20 PM
 */
session_start();

require_once('../app/Loader.php');
use app\application\library\commonFunctions;
use application\controller\Mailer;
use application\controller\memberController;

$functions = new commonFunctions();
$details = new memberController();
$settObj = new Mailer();

foreach ($_POST as $key => $value) {
    $$key = $value;
}

$ref_no = $functions->cleanInputs($ref_no);

$password = $functions->generateRandomPassword();
$member_data = $details->getOnlineUserById($username);


if (!empty($member_data->e_mail)) {
    $subject = "PASSWORD RESET";

    $body = '<h4>Hi ' . $member_data->surname . ',</h4>
     <p> Your password reset request has been processed,<br>
                        Your new credentials are:- </p> <p><strong>Username: ' . $member_data->username . ' </strong></p>
                       <p><strong> Password: ' . $password . ' </strong></p>
                       <p> Please note The password is automatically generated by the system for you and thus we recommend that you visit
                        <a href="https://clients.cic.co.ke/" target="_blank">our homepage</a>
                		         immediately and change it.</p>';
    //SEND EMAIL HERE
    /*
    * initialize the email script
    * @returns true if send false otherwise
    */
    $send = $settObj->sendEmails($subject, $member_data->email, $body);


    if (!$send) {
        echo "mailError";
    } else {
        $new_pass = md5($password);
        $update = $details->resetPassword($new_pass, $ref_no);
        if ($update) {
            echo "reset";
        } else {
            echo "failed";
        }
    }
} else {
    echo "existence";
}





